(define (search-for-primes start count)
  (cond ((= count 0) (newline) (display " found count "))
        ((odd? start) (if (timed-prime-test start)
                        (search-for-primes (+ start 2) (- count 1))
                        (search-for-primes (+ start 2) count)))
        (else (search-for-primes (+ start 1) count))))

(define (timed-prime-test n)
  (newline) (display n) (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
    (report-prime (- (runtime) start-time)))
  (prime? n))
(define (report-prime elapsed-time)
  (display " *** ") (display elapsed-time))
