(define (sum term a next b)
  (if (> a b)
    0
    (+ (term a)
       (sum term (next a) next b))))
(define (cube x) (* x x x))

(define (integral f a b n)
  (define h (/ (- b a) n))
  (define (inc x) (+ x 1))
  (define (y k) (f (+ a (* k h))))
  (define (term k)
    (* (cond ((or (= k 0) (= k n)) 1)
             ((odd? k) 4)
             ((even? k) 2))
       (y k)))
  (* (/ h 3) (sum term 0 inc n)))

(integral cube 0 1 100)
(integral cube 0 1 1000)
