(define (celcius-fahrenheit-converter x)
  (c+ (c* (c/ (cv 9) (cv 5))
          x)
      (cv 32)))
(define (c+ x y)
  (let ((z (make-connector)))
    (adder x y z)
    z))
(define (c* x y)
  (let ((z (make-connector)))
    (multiplier x y z)
    z))
(define (cv x)
  (let ((z (make-connector)))
    (constant x z)
    z))
(define (c/ x y)
  (let ((z (make-connector)))
    (multiplier y z x)
    z))
(define C (make-connector))
(define F (celcius-fahrenheit-converter C))
(probe "Celcius " C)
(probe "Fahrenheit " F)
(set-value! C 100 'user)
