(define (eval expr env)
  (cond ((self-evaluating? expr) expr)
        ((variable? expr) (lookup-variable-value expr env))
        ((quoted? expr) (text-of-quotation expr))
        ((assignment? expr) (eval-assignment expr env))
        ((definition? expr) (eval-definition expr env))
        ((if? expr) (eval-if expr env))
        ((lambda? expr) (make-procedure (lambda-parameters expr)
                                        (lambda-body expr)
                                        env))
        ((begin? expr) (eval-sequence (begin-actions expr) env))
        ((cond? expr) (eval (cond->if expr) env))
        ((let? expr) (eval (let->combination expr) env))
        ((let*? expr) (eval (let*->nested-lets expr env) env))
        ((application? expr)
         (apply (eval (operator expr) env)
                (list-of-values (operands expr) env)))
        (else
          (error "Unknown expression type: EVAL" exp))))
(define (let*? expr) (tagged-list? expr 'let*))
(define (let*->nested-lets expr env)
  (let ((vars (cadr expr))
        (body (let-body expr)))
    (define (make-lets exprs)
      (if (null? exprs)
        body
        (list 'let (list (car exprs)) (make-lets (cdr exprs)))))
    (make-lets vars)))
